### ISSUE TITLE
The variable m_Content of ScrollRect has not been assigned.

### ISSUE THREAD

**Issue by alaattinbedir** [zhaozilong1988/UITableViewForUnity#21]
Hi,
Even though I assigned the content variable of ScrollRect in the inspector I got an exception. 

UnassignedReferenceException: The variable m_Content of ScrollRect has not been assigned.
You probably need to assign the m_Content variable of the ScrollRect script in the inspector.
UnityEngine.Object+MarshalledUnityObject.TryThrowEditorNullExceptionObject (UnityEngine.Object unityObj, System.String parameterName) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:710)
UnityEngine.Bindings.ThrowHelper.ThrowNullReferenceException (System.Object obj) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/BindingsHelpers.cs:61)
UnityEngine.RectTransform.get_sizeDelta () (at <df5201c718ba4b0da1a55dc9d7e138b2>:0)
UIKit.UITableView.ResizeContent (System.Int32 numberOfCells) (at Assets/UIKit/UITableView/UITableView.cs:255)
UIKit.UITableView.ReloadDataInternal (System.Nullable`1[T] startLocation, System.Nullable`1[T] startNormalizedPosition) (at Assets/UIKit/UITableView/UITableView.cs:447)
UIKit.UITableView.ReloadData () (at Assets/UIKit/UITableView/UITableView.cs:571)
GameController.reloadTableView () (at Assets/GameScene/Scripts/GameController.cs:1006)
GameController.myMoveNumberSingle (Number tahmin) (at Assets/GameScene/Scripts/GameController.cs:1828)
SendButtonClick.OnMouseDown () (at Assets/GameScene/Scripts/SendButtonClick.cs:90)
UnityEngine.SendMouseEvents:DoSendMouseEvents(Int32) (at /Users/bokken/build/output/unity/unity/Modules/InputLegacy/MouseEvents.cs:208)

Is it related to unity version or tableview library? I use 2023.2.14f1 version.

Thanks in advance.

**Comment by zhaozilong1988** [comment]
@alaattinbedir 
Sorry for the late rely.
Could you provide your project?

**Comment by zhaozilong1988** [comment]
I confirmed the error in the Unity6 preview, and I’ll check it. Thanks.

**Comment by zhaozilong1988** [comment]
I fixed this issue in the pull request above.

It seems that the ScrollRect in SampleTableView (GameObject) of SampleScene.unity3d was not serialized correctly in some situations in the Unity6 preview. I recreated the ScrollRect, and that resolved the issue.
